default_language_version:
  python: python3.11

exclude: |
    (?x)^(
        backend/.vscode/
    )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-json
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: check-toml
      - id: check-xml
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: detect-private-key
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: pretty-format-json
        args: ["--autofix", "--no-sort-keys",]
      - id: fix-byte-order-marker
      - id: name-tests-test
        args: ["--pytest-test-first"]
        exclude: backend/app/tests/datas/user_data.py

  # import排序，使用参数--trailing-comma，否则会去掉多行import最后的逗号，而black则加上
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--line-length=100", "--multi-line=3", "--trailing-comma"]

  # 格式化docstring
  - repo: https://github.com/myint/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        args: ["--in-place", "--black",]

  # 代码格式化ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      # Run the linter.
      - id: ruff
        args: ["--fix", "--preview", "--exit-non-zero-on-fix", "--line-length=100"]
        # Run the formatter.
      - id: ruff-format
        args: ["--line-length=100"]

  # 代码格式化black
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: ["--line-length=100"]

  # 代码格式化flake8 rules：https://www.flake8rules.com/
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        args: ["--max-line-length=100", "--ignore=E402,E501,E731,W503,W504,F401"]

  # 代码安全检测
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        exclude: ^backend/app/tests
        args: ["--severity-level=medium"]

  # 代码格式化autoflake
  - repo: https://github.com/myint/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args:
          [
            "--recursive",
            "--in-place",
            "--remove-all-unused-imports",
            "--expand-star-imports",
            "--remove-unused-variable",
            "--ignore-init-module-imports",
          ]

  # 检测硬编码的password，key，token等内容
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks

  # 在提交前使用系统pytest进行测试，仅测试标记为fast的单元测试.
  # 因pytest未找到单元测试返回码为5，需要安装pip install pytest-custom_exit_code进行调整
  - repo: local
    hooks:
      - id: tests
        name: run tests
        entry: pytest -v -m fast --suppress-no-test-exit-code
        language: system
        always_run: true
        pass_filenames: false
        types: [python]
        stages: [commit]

  # 在push到服务器前使用系统pytest进行测试
  - repo: local
    hooks:
      - id: tests
        name: run tests
        entry: pytest -x
        language: system
        types: [python]
        stages: [push]

  # 检测提交信息格式化
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: ["--strict"]
