version: "3.9"

services:
  app-test:
    profiles: ["test"]
    build:
      context: ./backend
      args:
        INSTALL_DEV: true
    restart: always
    command: sh -c "pytest"
    env_file: "./backend/.env"
    environment:
      - GUNICORN_WORKERS=1
    networks:
      - test

  app-dev:
    profiles: ["dev"]
    build:
      context: ./backend
    restart: always
    command:
      [
        "uvicorn",
        "app.main:app",
        "--reload",
        "--host",
        "0.0.0.0",
        "--port",
        "8080",
      ]
    env_file: "./backend/.env"
    environment:
      - GUNICORN_WORKERS=4
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - dev

networks:
  test:
  dev: